
version: '3.8'

services:
  it-helpdesk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it-helpdesk
    ports:
      - "8471:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
